create table if not exists "USERS" (
    ID INTEGER PRIMARY KEY UNIQUE,
    NAME TEXT NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    ROLL INTEGER
)

CREATE TABLE IF NOT EXISTS "SHARED" (
	"ID"	TEXT NOT NULL UNIQUE,
	"USER"	TEXT NOT NULL,
	"BASE_PATH"	TEXT NOT NULL,
	"FLAGS"	INTEGER,
	"CREATED_AT"	TEXT NOT NULL,
	PRIMARY KEY("ID")
)